 "amphitheater", "Amphithéâtre"
 "classroom", "Salle de cours"
"laboratory", "Laboratoire"
"computer-room", "Salle informatique"
"meeting-room", "Salle de réunion"
"chapel", "Chapelle"
"office", "Bureau"